### ISSUE TITLE
Broadcasts that can be spammed should have a cooldown

### ISSUE THREAD

**Issue by MyMQL** [LambdaGaming/SCP198#1]
Plugin broadcast dont end

**Comment by LambdaGaming** [comment]
All broadcasts coming from this plugin seem to be lasting 6 seconds like they should. Could you provide some details? What Exiled version are you using? When exactly do the endless broadcasts occur? Are you using the most recent version of the plugin?

**Comment by MyMQL** [comment]
I know why that happend. When you spam trying to throw it from your eq the broadcast just get longer. I think you should add a max time or something because if you spam for example E to use it the broadcast get very long. im using the latest exiled version.

**Comment by MyMQL** [comment]
And, can you add translate option? So i can translate that information from broadcast to polish?

**Comment by LambdaGaming** [comment]
I'll look into adding a cooldown for the broadcasts. As for the translations, I know exiled supports it but I'm not sure how to implement it, and I can't find any plugins that I could use as an example, but if you know of any post them here and I'll see what I can do.
